service: serverless
# app and org for use with dashboard.serverless.com
#app: virtual-se
#org: zrehan

# You can pin your service to only deploy with a specific Serverless version
# Check out our docs for more details
frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs14.x
  lambdaHashingVersion: 20201221

  # you can overwrite defaults here
  #  stage: dev
  #  region: us-east-1

  # you can add statements to the Lambda function's IAM Role here
  #  iamRoleStatements:
  #    - Effect: "Allow"
  #      Action:
  #        - "s3:ListBucket"
  #      Resource: { "Fn::Join" : ["", ["arn:aws:s3:::", { "Ref" : "ServerlessDeploymentBucket" } ] ]  }
  #    - Effect: "Allow"
  #      Action:
  #        - "s3:PutObject"
  #      Resource:
  #        Fn::Join:
  #          - ""
  #          - - "arn:aws:s3:::"
  #            - "Ref" : "ServerlessDeploymentBucket"
  #            - "/*"

  # you can define service wide environment variables here
  environment:
    #postgresql
    POSTGRESQL_HOST: 'localhost'
    POSTGRESQL_PORT: '5432'
    #common
    DB_NAME: 'success_virtual_se'
    USERNAME: 'postgres'
    PASSWORD: 'password'

functions:
  classifier:
    handler: src/functions/classifier.classifier
  receiver:
    handler: src/functions/receiver.receiver
